#!/usr/bin/env python3
"""Regenerate the opengl32 forwarder header for the Stormworks proxy.

The proxy must export the FULL opengl32 surface, not just what stormworks64.exe
imports: glu32.dll (and other system components) statically import a large set
of gl* entry points, and the loader rejects our DLL with "entry point not
found" if any imported name is missing.

Every real opengl32 export except the two defined in gl_proxy.cpp is
re-exported as a forwarder to a renamed copy of the system DLL
(opengl32_real.dll, placed beside our proxy by install.cmd). Forwarders are
emitted as linker pragmas (`/EXPORT:NAME=opengl32_real.NAME`) - the reliable
MSVC mechanism. wglGetProcAddress and wglSwapBuffers are exported from
gl_proxy.cpp via __declspec(dllexport); the GL 2.0+ entry points the mod hooks
are not opengl32 exports at all and are handed out through wglGetProcAddress.

The opengl32 export set is the GL 1.1 + WGL ABI and has been stable for
decades, so the generated header is committed. Re-run only if a Windows update
ever changes the surface: python scripts/gen_gl_forward.py
"""
import os
import struct

HOOKED = {"wglGetProcAddress", "wglSwapBuffers"}
REAL_DLL = "opengl32_real"
SYSTEM_DLL = r"C:\Windows\System32\opengl32.dll"
OUT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..",
                                    "src", "StormworksHeadTracking", "gl_forwards.h"))


def named_exports(path):
    d = open(path, "rb").read()
    e = struct.unpack_from("<I", d, 0x3C)[0]
    coff = e + 4
    optsz = struct.unpack_from("<H", d, coff + 16)[0]
    opt = coff + 20
    is64 = struct.unpack_from("<H", d, opt)[0] == 0x20B
    ddoff = opt + (112 if is64 else 96)
    exp_rva = struct.unpack_from("<I", d, ddoff)[0]
    nsec = struct.unpack_from("<H", d, coff + 2)[0]
    so = opt + optsz
    secs = []
    for i in range(nsec):
        b = so + i * 40
        vsz, va, rsz, rptr = struct.unpack_from("<IIII", d, b + 8)
        secs.append((va, vsz, rptr, rsz))

    def r2o(rva):
        for va, vsz, rptr, rsz in secs:
            if va <= rva < va + max(vsz, rsz):
                return rptr + (rva - va)
        raise ValueError("rva not in any section")

    o = r2o(exp_rva)
    nname = struct.unpack_from("<I", d, o + 24)[0]
    anames = struct.unpack_from("<I", d, o + 32)[0]
    ao = r2o(anames)
    names = []
    for i in range(nname):
        nrva = struct.unpack_from("<I", d, ao + i * 4)[0]
        no = r2o(nrva)
        names.append(d[no:d.index(b"\x00", no)].decode())
    return names


def main():
    names = named_exports(SYSTEM_DLL)
    forwarded = sorted(n for n in names if n not in HOOKED)
    lines = [
        "#pragma once",
        "// Auto-generated by scripts/gen_gl_forward.py - do not edit by hand.",
        "// Forwards every non-intercepted opengl32 export to opengl32_real.dll.",
        "// These are export NAMES read from the system DLL's name table - the OpenGL 1.1",
        "// and WGL ABI - and no Microsoft code, address or byte is reproduced here.",
        "",
    ]
    for n in forwarded:
        lines.append('#pragma comment(linker, "/EXPORT:%s=%s.%s")' % (n, REAL_DLL, n))
    lines.append("")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", OUT, "-", len(forwarded), "forwarders,", len(HOOKED), "hooked")


if __name__ == "__main__":
    main()
